[package]
name = "todo-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "todo-app"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui-ui-components = { path = "../../components" }

